# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  username: root
  password:
  strict: false
  pool: 5
  socket: '/tmp/mysql.sock'
  host: localhost


development:
  <<: *default
  database: elasticsearch_sample_development

test:
  <<: *default
  database: elasticsearch_sample_test
